spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true